#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd using a while loop and IFS.

# Open the /etc/passwd file for reading
while IFS=: read -r username _ uid gid gecos home shell; do
    # Extract the group name from /etc/group file
    group=$(grep -E "^([^:]+:){2}$gid:" /etc/group | cut -d ':' -f 1)

    # Extract the user ID info from /etc/shadow file
    shadow=$(grep -E "^$username:" /etc/shadow)

    # Extract the password from shadow entry
    password=$(echo "$shadow" | awk -F ':' '{print $2}')

    # Extract additional user ID info from shadow entry
    user_id_info=$(echo "$shadow" | awk -F ':' '{print $8}')

    # Print the formatted output
    printf "The user %s is part of the %s gang, lives in %s and rides %s.\n" "$username" "$group" "$home" "$shell"
    printf "User ID's place is protected by the passcode %s, more info about the user here: %s\n\n" "$password" "$user_id_info"
done < /etc/passwd
