#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and appends a message based on specific loop iterations.
count=1
while [[ $count -le 20 ]]; do
  case $count in
    4)
      echo "4 and bad luck from China"
      ;;
    9)
      echo "9 and bad luck from Japan"
      ;;
    17)
      echo "17 and bad luck from Italy"
      ;;
    *)
      echo $count
      ;;
  esac
  count=$((count + 1))
done
