#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and shows bad luck messages for specific iterations

counter=1

while [ $counter -le 20 ]; do
  case $counter in
    4)
      echo "4 -  Bad luck from China"
      ;;
    9)
      echo "9 -  Bad luck from Japan"
      ;;
    17)
      echo "17 -  Bad luck from Italy"
      ;;
    *)
      echo $counter
      ;;
  esac

  counter=$((counter + 1))
done
