#!/usr/bin/env bash
# This script displays the time from 0:01 to 12:59
hour=0
minute=1

# Print the time for 12 hours and 59 minutes
while [ $hour -lt 12 ]; do
    echo "Hour: $hour"
    
    while [ $minute -le 59 ]; do
        echo "$minute"
        minute=$((minute + 1))
    done

    hour=$((hour + 1))
    minute=1
done
